Assembler:Assembler.o PreProcessor.o FirstScan.o SecondScan.o Errors.o Utils.o Validation.o SymbolTable.o Files.o
	gcc -Wall -g -ansi -pedantic Assembler.o PreProcessor.o FirstScan.o SecondScan.o Errors.o Utils.o Validation.o SymbolTable.o Files.o -o Assembler

Assembler.o:Assembler.c 
	gcc -Wall -c -ansi -pedantic Assembler.c -o Assembler.o

Files.o:Files.c 
	gcc -Wall -c -ansi -pedantic Files.c -o Files.o

PreProcessor.o:PreProcessor.c 
	gcc -Wall -c -ansi -pedantic PreProcessor.c -o PreProcessor.o

FirstScan.o:FirstScan.c 
	gcc -Wall -c -ansi -pedantic  FirstScan.c -o FirstScan.o

Errors.o:Errors.c 
	gcc -Wall -c -ansi -pedantic Errors.c -o Errors.o

Utils.o:Utils.c 
	gcc -Wall -c -ansi -pedantic Utils.c -o Utils.o

Validation.o:Validation.c 
	gcc -Wall -c -ansi -pedantic Validation.c -o Validation.o

SymbolTable.o:SymbolTable.c 
	gcc -Wall -c -ansi -pedantic SymbolTable.c -o SymbolTable.o

SecondScan.o:SecondScan.c 
	gcc -Wall -c -ansi -pedantic SecondScan.c -o SecondScan.o



